# Generated by Django 4.2.30 on 2026-04-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_extra_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_receive_71134e_idx',
            old_name='chat_msg_recv_send_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_receive_14362e_idx',
            old_name='chat_msg_recv_read_idx',
        ),
    ]
